apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    component: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ftps
  template:
    metadata:
      labels:
        component: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-test
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 60000
        - containerPort: 60001
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  type: LoadBalancer
  selector:
    component: ftps
  ports:
  - name: controll
    protocol: TCP
    port: 21
    targetPort: 21
  - name: trans-1
    protocol: TCP
    port: 60000
    targetPort: 60000
  - name: trans-2
    protocol: TCP
    port: 60001
    targetPort: 60001
