apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    component: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      component: wordpress
  template:
    metadata:
      labels:
        component: wordpress
    spec:
      containers:
      - name: wp-test
        image: wp-test
        imagePullPolicy: Never
        ports:
        - containerPort: 80
