version: '3'

services:
    mysql:
        image: mysql_test
        restart: always
        ports:
            - 3306:3306

    wordpress:
        image: wp_test
        ports:
            - 5000:5000
        depends_on:
            - mysql
        restart: always
        tty: true
