apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  type: LoadBalancer
  selector:
    component: wordpress
  ports:
  - name: wordpress
    protocol: TCP
    port: 5050
    targetPort: 80
