apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    component: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      containers:
      - name: influxdb
        image: inf-test
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: inf-pv
          mountPath: "/var/lib/influxdb"
      volumes:
      - name: inf-pv
        persistentVolumeClaim:
          claimName: inf-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inf-service
spec:
  type: ClusterIP
  selector:
    component: influxdb
  ports:
  - name: influxdb
    protocol: TCP
    port: 8086
    targetPort: 8086
