apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: inf-pv