apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
      - name: mysql-test
        image: mysql-test
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-volume
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: clusterIP
  selector:
    component: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
