apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    component: ftps
spec:
  replicas: 2
  selector:
    matchLabels:
      component: ftps
  template:
    metadata:
      labels:
        component: ftps
    spec:
      containers:
      - name: ftps-test
        image: ftps-test
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gra-service
spec:
  type: LoadBalancer
  selector:
    component: grafana
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
