apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    component: phpmyadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      component: phpmyadmin
  template:
    metadata:
      labels:
        component: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: pma-test
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: LoadBalancer
  selector:
    component: phpmyadmin
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 80
