apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    component: influxdb
spec:
  replicas: 2
  selector:
    matchLabels:
      component: influxdb
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      containers:
      - name: inf-test
        image: inf-test
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: inf-service
spec:
  type: LoadBalancer
  selector:
    component: influxdb
  ports:
  - name: influxdb
    protocol: TCP
    port: 8086
    targetPort: 8086
